### ISSUE TITLE
[Bug] Potential obfuscation of program-terminating error

### ISSUE THREAD

**Issue by gerelef** [KonstantinosRekoumis/CSR#15]
[There's a code segment in plate.py](https://github.com/KonstantinosRekoumis/CSR/blob/3940a6e8611b1614df32a8cd45bf0679c2720f39/modules/baseclass/plate.py#L239-L252) (copied for convenience):
```python3
except KeyError:
    print("The axis dictionary is not properly structured")
    return 0
except TypeError:
    print(
        "The axis dictionary has no proper values.\n",
        "axis :",
        axis["axis"],
        type(axis["axis"]),
        "\noffset :",
        axis["offset"],
        type(axis["offset"]),
    )
    return 0
```
Shouldn't the program die if the axis dictionary values are improper(ly structured)?

**Comment by KonstantinosRekoumis** [comment]
I see your point and it makes sense. As this function is called in the backend part of the program it should terminate the program, because it points to bad setup of the backend code. I propose the following change:
```py
except KeyError:
    Logger.error("The axis dictionary is not properly structured")
except TypeError:
    Logger.error(
        "The axis dictionary has no proper values.\n",
        "axis :",
        axis["axis"],
        type(axis["axis"]),
        "\noffset :",
        axis["offset"],
        type(axis["offset"]),
    )
```
