### ISSUE TITLE
[Bug] TEX_PREAMBLE missing in DataLogger.py

### ISSUE THREAD

**Issue by gerelef** [KonstantinosRekoumis/CSR#18]
TEX_PREAMBLE is not used anywhere in DataLogger, even though it's meant to be used with `standalone=True`
![image](https://github.com/KonstantinosRekoumis/CSR/assets/44060598/ccc67b6b-8e52-4c21-9046-d0ddb6a41e04)

**Comment by KonstantinosRekoumis** [comment]
Done in merge of pull request #20

**Comment by gerelef** [comment]
> Done in merge of pull request #20

I'm pretty sure it isn't done in that pull request.
