### ISSUE TITLE
Implement the Standalone behavior for the LaTeX output functions

### ISSUE THREAD

**Issue by KonstantinosRekoumis** [KonstantinosRekoumis/CSR#21]
During the latest refactoring of the codebase the LateX export functions lost their full functionality. 
Standalone behavior is a feature that is currently missing.

Also might as well implement more features in the Standalone Report like ToC, ToF, etc.

Running the commands to build the report may be a useful addition as well.

**Comment by gerelef** [comment]
What's the status on this? Is this actively being worked on?

**Comment by gerelef** [comment]
This was resolved with cae4739c3e67325a84bd6c065b020af562346a24, please close.
