### ISSUE TITLE
Deepen project structure hierarchy to reduce number of classes in specific grossly overloaded "god files"

### ISSUE THREAD

**Issue by gerelef** [KonstantinosRekoumis/CSR#5]
## Issue
Some files currently suffer from being "god files" if you will, since they are thousands of lines long for no good reason; they just a lot of different classes in the same file. This makes it harder to collaborate on different parts of the project with multiple, since everything is coupled together on the same file, making the experience of merge requests significantly worse.

## Proposal
Split every class to it's own file & create directories according to responsibility, rather than inserting everything in the same file.
Files with very similar functionality should be on the same directory depth.

**Comment by KonstantinosRekoumis** [comment]
Working on it

**Comment by KonstantinosRekoumis** [comment]
Did changes to that direction see latest [commit](https://github.com/KonstantinosRekoumis/CSR/commit/6087b13aa705ab8cab0c7c235b5a7fea9167f14b)

**Comment by gerelef** [comment]
looks good right now, I'll take a deeper look later
note: [you can link commits and pull requests with specific issues ](https://gitdailies.com/articles/link-github-commit-to-issue/)

**Comment by gerelef** [comment]
Please add input on whether or not this issue is finished. I think with the latest PR, this is ready to be closed.
